# Generated by Django 4.1.13 on 2025-01-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(unique=True)),
                ('new_slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
