# Generated by Django 4.1.13 on 2025-01-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Redirect',
        ),
    ]
