# Generated by Django 5.1.5 on 2025-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_is_in_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='base price if not specified in products variant', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the product's base price.", max_digits=10, null=True),
        ),
    ]
