# Generated by Django 5.1.5 on 2025-02-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='digital_files/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='filesize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
