# Generated by Django 5.1.5 on 2025-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productvariant_dimensions_productvariant_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed product description with features, specifications, etc.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='List key features or bullet points (e.g., HTML or Markdown)', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], default='physical', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price if not specified in product variants', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Short description of the product'),
        ),
    ]
