# Generated by Django 5.1.5 on 2025-02-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Upload a file if this is a digital product', null=True, upload_to='digital_files/'),
        ),
    ]
